language: python
python:
- '3.6'
install:
- pip install ansible>=2.4.0 'molecule[gce]' apache-libcloud paramiko
- molecule --version
before_install:
- openssl aes-256-cbc -K $encrypted_7ca6f6f13ce7_key -iv $encrypted_7ca6f6f13ce7_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
script:
- molecule --debug create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: LbCEalOjetEbR6Dglfl500fwzknysVsZXg/n5eNKyTqG0QsojZQR+5RstIqbvHQuViGSwkmIGJTTQOsrS7D8lZuIp7LwWlRTkWYVWz3xQ7S8CnoZQNigf3ELQdArLAEQ4sVZJ0H4qOo88hwNLanmUFUSf/gTq1ZNCjmPy14tWlrRz65HwsAk6EJ4V7XSx6BAtJ6X2v/nApu2xZ8iCqSCZNOpanbq2Xj/Jqh4NGCMHZUFg93n4EoabdQHW4gsqb4NVC2UTBXhsxsCFNEtYaProWJaZ5pPP5qItrvMbBbn2vHIaVF1Uldwlvg3b7fEIGfmdcVETyUoPyiEFNxUIC4aFPnXtbPv/ar6kXaMy5KYkN0NbTNreReOZ08Yncg2eznMWWQ7HJbRzAhDh5xiZL92eEuhAXkIx2EgnLgChqapMuhcKhmJQopi1QmHY44cQ77CoQgbzuGGIBWt7S32DetXH+oIDQ7zAzimc+d035BLx7MeC8lypHnppzo97HjugPJtuEIy2ZNsrj3SH7oJyLgQ9rj+ECisW+C/H2wOXnCatK16bbZP19AbEvJ+5/LnLqOy0/S8fDl/5IYJRkBbmWLMDXX8sFMO8YAfYrISnUw8CjRDyHSfi7P+X5BY/sx5YzqC5yFKk9inQkk677iZo5fXR115u/5hTz7Wm1j/GeW4sso=
dd:
  secure: Ptwa7MqmCFa8JUy0bek12O64SgdTp06zAx65rwkr8MWyQnFVAhBQwPgHxFpCE1lY6roYP829s856B8sFDWW+JFHJimU71vcHqlhYY2UPVG100+0U0tcT0TZngteflEmigGpAy4ShKKWmaAf2D4HIAehTTuOCd++LqQMCPuJnk1gkC3PR09c1TVpsdvIvJfpIZLGHFoUlB729LGvHbSSp/cVZCpUM1eUnqDgqmIA8Nq+kH/Iw7Ufg74Mg1YfRx3ci8qkeKIUbTXeazKf6PQJwvjhw7oz34EKbwpXvGBKvGmmiZRHkyi0oTEItObVi6v/+NaPIJyF4t6CiydDTtOkRT+PKIwYaIsHmUABdtisxquTwMgukT0v1W0zp6YQOI/mYdoKCDRqr8oLFJ2sB0GkbEMO4+be/xFItMyz3mj6LG3KF+a2N5tVa57VIgvGzYP+YioLSNSFSVg+c6WiJtMbBm8qMGn3uyJZzjdlc6QVTR6OaZKqn1+MEQkoAYKpDQbwaWwAOR3QGDPN9IRsSUcsCRGcPLbPoo9jwXcfUvu8WJq/T3D2BTErfMP+rYZVJ0I8FBrxzPk4p9X9iCFFrK/eMj00d/IhPuZfNq9StMMqmXSwcT+Bx9HrFmbq0mRv6KGqqQdryEu+nyCQ/EFj7HFsK13x2Zr1XwPYuEMWMGXyzLDY=
env:
  global:
  - secure: vD4mxrVmOtYXEAsTGOcLw+/ZvUpVbZGYJPW4HbBSDf7tJsYkQU3Zj44vqzvEAUBoq817CVkiPmEzQ9R/wbWAoAF04PifmrrCyGBBTOKfuckUyombu53g3K8q/oZ2aYlCPab5qoQvJqX517nTOhyPjiAf7HYcJtrW1KhkXODuAgwN3DBEY710wTYSLFWg50+3nJlcATxgaLJYLc8bG3BjbWNH8N/sHdeWhddoCe2zQ01IJvVoxc/SgpCeU9C/DTH+lenogqrTmOW/ExVB1QstVlL7wGrTcOE4zaPQm27bIHyfPCwHEpPwB9cwZjUKDYlR26KacSSBTJlCvnEjGkctd5yntZbr3uASK+zhD9VmB4ki1j9mIjLcexjHGUnBBv8TH1cx/bHkemIamUMtKiqAK6zDmhWyvjXpdogviyJ/Jhu1y/Ht4Gquomhlrz69WW/LzlKYm5PVoM5neGXd7aBj3yduUGCGcolGMJnQWY15tiOl8SEai+ApgqEHYmCmu8hBbymdxSBhCnPpkP9UOe5CRdat3Y004sRHk9K+1ApD4U9F6WVhvYUafb5h6psqFHbNrDjopc+0xdW7a4SN4ojO6OMp7N4j3rcougrsdwKUTtaR6aFMMETbwJpa/oV1zJRatrFGOksyR/4aEwZRWbIkjwzXXioPECCZdd+Ab+IIg/8=
  - secure: 2F2l/F7cFSWx6gUJYJuzVEBF4NOj7HAzQvv8Ie/JGu4Uhgxx7hWFBgH7jQvogBMDRIDLBsAMuARu2LLRkDdnzhzAL4CZTqisS7tLMQSAvXtnlB5mmsKKHeUCv1Znh6bDzygWCaQ/BPOFwJB/qADkWF6FfU5TFqUXgOOTc5I+HIAFzsNhZZeEakhaEnRfiUWeOpS32CRlqFp/EC+tM1eYG00aS2iV+1Otz7NOnll/zs0Mvbc2KL57kH1XI0vvvHWYkkqwPg372+KaWfPZY1ERHEfzteIlceUG0dV3C0bV0Xnq5azhhMy42Vv0Xxd2Lqa+n7XqlwlKN6Exs2lefutcwceeTzhQVhx+msDlSn2g/MfcVIyMvWXqNHe6Il1UnSehmFpJHTJH2+rbtqmW/LTLSsPww8bF2UofufYPxG/RyG3ZGED7FgsXsMZrcwfO2IdLwaRLJhIralbBQokzHdas41mlzeX4mzn0oR8hnUfD8narNCeiVbqZ1N+2vgQDKhyDqnZonuhzroedYf8vqwg7kjOzecCwdH69/PFQ2ECoGk72FiuvPKgXz2KsvsqjzqWELi6szOoVr37eV/k7u/Z5fR6sIHcOr5wUXael18wMsUzVSdmevibRzhMVehT8qtIbI6x52rEX0swoMEu3KWK9yvk/cPYmcz5o+bRE+NnSr7M=
