language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud paramiko
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
dd:
  secure: HaPf0vFq7jcMHuLSFc32DLA6H5QBXV5aM3orLnUmvS1jxi0Q/icgjVtvS9G3Acx3tdjbBLKOtgJ2lRJrattrlr8DtPg6EINRgzqo6L2Z+OocCGhWtyvnzBE6jCYEXiCLtbJUOnW+GJ63iFb/Rxsevax1mUCaJ1QRulFZn09U4Rq519wl8UvXtVC2PZwZtcBFF8buJEnBA3ka5TepwX5wVn19U3difLUp3KbnbRGSjHmwRWWqnqBPUXcCmf5EyEu9jwsbApchs1Y63XPB5vxMuuIVxwCNFQ4emUtWblUJtAaRC7obTsw9aMCYR4LKYjFxhmPshvHR1OVB1s7Zy6PrRec/hvlKT3grr4fE2kCwxQXy3V/uCrQq+jUfFb/pWQmDjBr1/tNYuickuphsqFYP1b/AClHkALZKNi9PPl9cbELumcxDopEW7l47QuoxIrWOlP2wFz0LK7v1zNHfbK/RZQS7vzbCRYAsCffqQpR+IPPW68mBXipvC5/eELQzauKvbW3IgoFhLMnrHc45CxiUEwRfmiVAtRKC73kzlo/yY6TJpT+nPuEKd5w7m9srEfIvgZBhrvxsAZ9rhl02qN43J2DdMYuWx7aC7EpCn0t0vQiAbv8HY9FNhRBIbgLx5S0IPxabYqs0P2vx4N58/OhzUIuTexoQagSinS9Fp8PQTpg=
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: wAas6lOxPi8DctPxbmE0JryzJOKfTob4igppgHpHv/Id+bM6RUNe1UmyrC3JHN8RHASsxPHOyPgm1ziids1z8VwNY2sbHKl4jj9p8zaxUIyc/sNfX935tQMaWkq18jC+lNwtnoCR0ggcxv+43szL7KlsdkQ/qG+9wh0SIxZW8vuUUUd7ABUqUpVRzgMVhTYvNRgxtAyjlpsdIjPch6E5xh4U/DBo800+XvO6/plT2A7RqWXJNl189r83WVHpFy43eH232u7kYdQ3jj2CL5+A6/ArhcL7JvmSOO9Unts+LBUbcCa1XER3dMaSsRUzROAaUeXpObLTkvFVul+h5waOhkcX1zviHN8+Yq0r//lR039BZlZZNPvf+Undbc9/FGhEpHhzXg74FNARHfOIKNMDhoR0z0AfbchfVOcrATcjIyYdRH2I2FuyuWfritBBc7wBdG+QVNmuqMnw7hh6Qf4qybNBNDKt5F4eHtsBi3WIC6gQayH8ojM62CijGEniywantA43JDKg6VXVr4lC3sLY1IXdW4GvHF4yYHqvWG+OUzFQI5N8gTTK1OhV4fXH7orx1nMmsbdlwsINleVBsKmZ7C8+DJrWq0+No1jUIPyMCWcoci6n7NMH0QgvrnRwtbqJmNMeAWaCqVfNmvrSBpzasCfNw6QtWXvOsFHyBDJrZXw=
  - secure: J8+7mlTKKHjQmkmGyZzVBWaKYLh51qt113CvK3VFkAqpI74NSx64moT6UBpWFq4U2yEYv0lFt+PXiztabuQ2m+9gBP4/fdgpR/wmUJitSo8OIV2SRfXCEyihYf/soQVP7dvy5vtGdSip/Iht/26+Owp2IsKxsoUH3P0bLY1Pi25Bm3WFgRoveroAWLyVtQO8SeD0W2DhqDUWukelTSV2Ej0ToA4qPkbF69mUhgycdnEwS0yP5l1z9+PZ4HoY7aGhu6e+fv1VMLC+kH6IWeh+KZ+5cWFV6SCJX+aPQ3PjeZg0q137OrklBSe9Q8OyEKmgzs/EiZ9rP2wNQIEfTBpvs3SDC8rWIqrgd5tB7T3jr2cBmoZFnmMw7T4DiHo5hSw6m0+6uqzHRsyhqjVS/XBRfY10VVSoRXFwEU56gCnbjRbIXjkXUD4i9Ik7VrHeTzjuoF5Y9pVtICWjlDHtWvpW+QBA8JFK8c6qZB0f5Ra2gZqqlCwes3m3rZxN2g1PE8kblDM7qabvZyPXYOsyHaPwCnTq1LGQdPS457hOzApfjmT+D0NSZWYKGakD8D8DEqKhsgWf8wu1RoiVcuwuH6ktCGEpuepU/7/ZhApt8InsYbiWeUbsi1P5CLSWEuOAiBHDT7wLap5gDQ0XJU7dV+rRiXry1GGxiIVZnAs/dHgunBE=
before_install:
- openssl aes-256-cbc -K $encrypted_7ca6f6f13ce7_key -iv $encrypted_7ca6f6f13ce7_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
